START:

use DBI;
use DBD::Oracle qw(:ora_types);
use Excel::Writer::XLSX;
use Excel::Writer::XLSX::Utility;
use Text::CSV_XS;
#use DateKey_ARC;
use DBConnector;
use Win32::Job;
use Getopt::Long;
use IO::File;
use MIME::QuotedPrint;
use MIME::Base64;
use Mail::Sendmail;
use HTML::Entities;
use HTML::Table::FromDatabase;
use Date::Calc qw( Today Add_Delta_Days Month_to_Text);

($year,$month,$day) = Today();
$month_to_text = Month_to_Text($month);

$test_query = qq{ SELECT CASE WHEN EXISTS (SELECT *
					FROM ADMIN_ETL_LOG 
					WHERE TO_DATE(LOG_DATE, 'DD-MON-YY') = TO_DATE(SYSDATE,'DD-MON-YY') AND TASK_ID = 'AggDlyStrDept' AND ERR_CODE = 0) THEN 1 ELSE 0 END STATUS 
					FROM DUAL };

$tst_query = $dbh->prepare($test_query);
$tst_query->execute();

while ( my $x =  $tst_query->fetchrow_hashref()){
	$test = $x->{STATUS};
} 


if ($test eq 1){

	 $date = qq{ 
	SELECT WEEK_NUMBER_THIS_YEAR, DATE_KEY, DATE_FLD, WEEK_ST_DATE_KEY, WEEK_END_DATE_KEY,  YTD_DATE_KEY, YTD_DATE_FLD,YTD_DATE_KEY_LY, YTD_DATE_FLD_LY, MONTH_UPD1, MONTH_UPD2  FROM
	  (SELECT WEEK_NUMBER_THIS_YEAR, DATE_KEY, TO_CHAR(DATE_FLD, 'DD Mon YYYY') DATE_FLD, WEEK_ST_DATE_KEY, WEEK_END_DATE_KEY 
		FROM DIM_DATE
		WHERE DATE_FLD = (SELECT AGG_DLY_END_DATE_FLD FROM ADMIN_ETL_DATE_PARAMETER)),
	  (SELECT DATE_KEY YTD_DATE_KEY, DATE_FLD YTD_DATE_FLD, DATE_KEY_LY YTD_DATE_KEY_LY, DATE_FLD_LY YTD_DATE_FLD_LY
		FROM DIM_DATE_PRL WHERE MONTH_NAME = (SELECT TO_CHAR(SYSDATE-14, 'MON') AS MONTH_UPD1 FROM DUAL) AND DAY_IN_MONTH = 1 AND YEAR = (SELECT TO_CHAR(SYSDATE, 'YYYY') AS YEAR FROM DUAL)),
	  (SELECT TO_CHAR(SYSDATE, 'MON') AS MONTH_UPD2, TO_CHAR(SYSDATE-14, 'MON') AS MONTH_UPD1 FROM DUAL)

	 };
	 
	

	my $sth_date_1 = $dbh->prepare ($date);
	 $sth_date_1->execute;

	while (my $x = $sth_date_1->fetchrow_hashref()) {
		$wk_st_date_key = $x->{WEEK_ST_DATE_KEY};
		$wk_en_date_key = $x->{DATE_KEY};
		$wk_number = $x->{WEEK_NUMBER_THIS_YEAR};
		$as_of = $x->{DATE_FLD};
		$yr_st_date_key = $x->{YTD_DATE_KEY};
		#$yr_st_date_key = 1096;
		$yr_st_date_fld = $x->{YTD_DATE_FLD};
		#changed 21-Mar-16 to fix MTD lacking 1st day of the month
		$yr_st_date_key_ly = $x->{YTD_DATE_KEY_LY}-1;
		#$yr_st_date_key_ly = 731;
		$yr_st_date_fld_ly = $x->{YTD_DATE_FLD_LY};
		$upd_per1 = $x->{MONTH_UPD1};
		$upd_per2 = $x->{MONTH_UPD2};
	}

	$date_2 = qq{ 
	SELECT DATE_KEY1, TO_CHAR(DATE_FLD1, 'DD Mon YYYY') DATE_FLD1, DATE_KEY_LY1, TO_CHAR(DATE_FLD_LY1, 'DD Mon YYYY') DATE_FLD_LY1, DATE_KEY2, TO_CHAR(DATE_FLD2, 'DD Mon YYYY') DATE_FLD2, DATE_KEY_LY2, TO_CHAR(DATE_FLD_LY2, 'DD Mon YYYY') DATE_FLD_LY2, DATE_KEY3, DATE_FLD3, MONTH_ST_DATE_KEY, MONTH_END_DATE_KEY, QUARTER, YEAR FROM
		(SELECT DATE_KEY AS DATE_KEY1, DATE_FLD AS DATE_FLD1, DATE_KEY_LY AS DATE_KEY_LY1, DATE_FLD_LY AS DATE_FLD_LY1
		FROM DIM_DATE WHERE DATE_KEY = $wk_st_date_key),
		(SELECT DATE_KEY AS DATE_KEY2, DATE_FLD AS DATE_FLD2, DATE_KEY_LY AS DATE_KEY_LY2, DATE_FLD_LY AS DATE_FLD_LY2
		FROM DIM_DATE WHERE DATE_KEY = $wk_en_date_key),
		(SELECT DATE_KEY AS DATE_KEY3, DATE_FLD AS DATE_FLD3, MONTH_ST_DATE_KEY, MONTH_END_DATE_KEY
		FROM DIM_DATE_PRL WHERE TO_CHAR(DATE_FLD, 'DD Mon YYYY') = '$as_of'),
		(SELECT QUARTER, YEAR FROM DIM_DATE_PRL WHERE TO_CHAR(DATE_FLD, 'DD Mon YYYY') = '$as_of')
	 };

	my $sth_date_2 = $dbh->prepare ($date_2);
	 $sth_date_2->execute;
	 
	while (my $x = $sth_date_2->fetchrow_hashref()) {
		$wk_st_date_key_ly = $x->{DATE_KEY_LY1};
		$wk_en_date_key_ly = $x->{DATE_KEY_LY2};
		#$wk_st_date_key_ly = 819;
		#$wk_en_date_key_ly = 822;
		$wk_st_date_fld = $x->{DATE_FLD1};
		$wk_en_date_fld = $x->{DATE_FLD2};
		$wk_st_date_fld_ly = $x->{DATE_FLD_LY1};
		$wk_en_date_fld_ly = $x->{DATE_FLD_LY2};
		#$wk_st_date_fld_ly = 819;
		#$wk_en_date_fld_ly = 822;
		$mo_st_date_key = $x->{MONTH_ST_DATE_KEY}-1;
		$mo_en_date_key = $x->{DATE_KEY3};
		$quarter = $x->{QUARTER};
		$year = $x->{YEAR};
	}

	$date_3 = qq{ 
	SELECT DATE_KEY1, TO_CHAR(DATE_FLD1, 'DD Mon YYYY') DATE_FLD1, DATE_KEY_LY1, TO_CHAR(DATE_FLD_LY1, 'DD Mon YYYY') DATE_FLD_LY1, 
		   DATE_KEY2, TO_CHAR(DATE_FLD2, 'DD Mon YYYY') DATE_FLD2, DATE_KEY_LY2, TO_CHAR(DATE_FLD_LY2, 'DD Mon YYYY') DATE_FLD_LY2,
		   DATE_KEY3, TO_CHAR(DATE_FLD3, 'DD Mon YYYY') DATE_FLD3, DATE_KEY_LY3, TO_CHAR(DATE_FLD_LY3, 'DD Mon YYYY') DATE_FLD_LY3 FROM
		(SELECT DATE_KEY AS DATE_KEY1, DATE_FLD AS DATE_FLD1, DATE_KEY_LY AS DATE_KEY_LY1, DATE_FLD_LY AS DATE_FLD_LY1
		FROM DIM_DATE_PRL WHERE DATE_KEY = $mo_st_date_key-1),
		(SELECT DATE_KEY AS DATE_KEY2, DATE_FLD AS DATE_FLD2, DATE_KEY_LY AS DATE_KEY_LY2, DATE_FLD_LY AS DATE_FLD_LY2
		FROM DIM_DATE_PRL WHERE DATE_KEY = $mo_en_date_key-1),
		(SELECT DATE_KEY AS DATE_KEY3, DATE_FLD AS DATE_FLD3, DATE_KEY_LY AS DATE_KEY_LY3, DATE_FLD_LY AS DATE_FLD_LY3
		FROM DIM_DATE_PRL WHERE QUARTER = $quarter AND YEAR = $year AND MONTH_IN_QUARTER = 1 AND DAY_IN_MONTH = 1)
	 };

	my $sth_date_3 = $dbh->prepare ($date_3);
	 $sth_date_3->execute;
	 
	while (my $x = $sth_date_3->fetchrow_hashref()) {
		$mo_st_date_key_ly = $x->{DATE_KEY_LY1};
		#$mo_st_date_key_ly = 790;
		$mo_en_date_key_ly = $x->{DATE_KEY_LY2};
		$mo_st_date_fld = $x->{DATE_FLD1};
		$mo_en_date_fld = $x->{DATE_FLD2};
		$mo_st_date_fld_ly = $x->{DATE_FLD_LY1};
		#$mo_st_date_fld_ly = '01 Mar 2015';
		$mo_en_date_fld_ly = $x->{DATE_FLD_LY2};
		$qu_st_date_key = $x->{DATE_KEY3};
		$qu_st_date_key_ly = $x->{DATE_KEY_LY3};
		$qu_st_date_fld = $x->{DATE_FLD3};
		$qu_st_date_fld_ly = $x->{DATE_FLD_LY3};
		
#$event_st_date_key = 990; #08-apr-15
#$event_en_date_key = 993; #15-MAR-15
	}

	printf "Test ETL Status = ". $test ." \nArc BI Sales Performance Part 1\nGenerating Data from Source \n";
	
	&generate_csv_sales;
	&generate_csv_sales_wtd;
	
	#&generate_instock;
	
	my $job1 = Win32::Job->new;
	$job1->spawn( "cmd" , q{cmd /C "DSP_Jobs.pl pause"});
	$job1->run(25000);
	
	&mail;
	
	$tst_query->finish();
	$dbh->disconnect; 
	
	exit;
	
}

elsif ($test eq 0){
	print "Test Status = ". $test ." \nETL still running\n";
	
	$tst_query->finish();
	
	sleep(300);
	
	goto START;
}
 

sub generate_csv_sales {

print "Deleting sales data from ". $upd_per1 ." to ". $upd_per2." of table METRO_IT_SALES_DEPT... \nPreparing to insert new data... \n";

$test = qq{ 
DECLARE
TYPE sd_tab IS TABLE OF METRO_IT_SALES_DEPT%ROWTYPE;
sales_dept_tab   sd_tab := sd_tab();

BEGIN

SELECT * BULK COLLECT INTO sales_dept_tab 
FROM 
(
SELECT 
MONTH_IN_YEAR, PER, 
STORE_FORMAT,
STORE_FORMAT_DESC, 
STORE_CODE, STORE_DESCRIPTION, 
MERCH_GROUP_CODE, MERCH_GROUP_DESC, 
GROUP_CODE, GROUP_DESC, 
DIVISION, DIVISION_DESC, 
DEPARTMENT_CODE, DEPARTMENT_DESC, 
NEW_FLG, MATURED_FLG, 
CASE WHEN TARGET_SALE_VAL IS NULL THEN 0 ELSE TARGET_SALE_VAL END AS TARGET_SALE_VAL, 
CASE WHEN SALE_TOT_QTY_OTR_TY IS NULL THEN 0 ELSE SALE_TOT_QTY_OTR_TY END AS SALE_TOT_QTY_OTR_TY, 
CASE WHEN NET_SALE_OTR_TY IS NULL THEN 0 ELSE NET_SALE_OTR_TY END AS NET_SALE_OTR_TY, 
CASE WHEN SALE_TOT_QTY_OTR_LY IS NULL THEN 0 ELSE SALE_TOT_QTY_OTR_LY END AS SALE_TOT_QTY_OTR_LY, 
CASE WHEN NET_SALE_OTR_LY IS NULL THEN 0 ELSE NET_SALE_OTR_LY END AS NET_SALE_OTR_LY, 
CASE WHEN SALE_TOT_QTY_CON_TY IS NULL THEN 0 ELSE SALE_TOT_QTY_CON_TY END AS SALE_TOT_QTY_CON_TY, 
CASE WHEN NET_SALE_CON_TY IS NULL THEN 0 ELSE NET_SALE_CON_TY END AS NET_SALE_CON_TY, 
CASE WHEN SALE_TOT_QTY_CON_LY IS NULL THEN 0 ELSE SALE_TOT_QTY_CON_LY END AS SALE_TOT_QTY_CON_LY, 
CASE WHEN NET_SALE_CON_LY IS NULL THEN 0 ELSE NET_SALE_CON_LY END AS NET_SALE_CON_LY,
SYSDATE AS UPDATE_DATE,
TO_CHAR(SYSDATE, 'YYYY') YEAR

FROM (
SELECT 
BASE.MONTH_IN_YEAR, 
BASE.PER, 
CASE 
	WHEN (BASE.STORE_CODE IN ('2001', '2002', '2003', '2004', '2006', '2007', '2009') AND ( (BASE.MERCH_GROUP_CODE = 'DS') OR (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 9000) OR  (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE != 8040) ) ) THEN '1'
	WHEN (BASE.STORE_CODE IN ('2001', '2002', '2003', '2004', '2006', '2007', '2009') AND ( (BASE.MERCH_GROUP_CODE = 'SU') OR (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8500) OR  (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE = 8040) ) ) THEN '2'
	WHEN BASE.STORE_CODE IN ('2223','2102','2101') THEN '1'
	WHEN BASE.STORE_CODE IN ('2013', '2012', '4004', '3009', '3010', '3011', '2001W', '3012') THEN '2'
	WHEN BASE.STORE_CODE IN ('2005','2008','2010','2011','6001', '6002', '6003', '6004', '6005', '6012', '6009', '6010', '6011','6013') THEN '4'
	WHEN BASE.STORE_CODE IN ('3001', '3007', '4003', '3002', '3003', '3004', '3005', '3006') THEN '2'
	ELSE BASE.STORE_FORMAT END AS STORE_FORMAT, 
CASE 
	WHEN (BASE.STORE_CODE IN ('2001', '2002', '2003', '2004', '2006', '2007', '2009') AND ( (BASE.MERCH_GROUP_CODE = 'DS') OR (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 9000) OR  (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE != 8040) ) ) THEN 'Department Store'
	WHEN (BASE.STORE_CODE IN ('2001', '2002', '2003', '2004', '2006', '2007', '2009') AND ( (BASE.MERCH_GROUP_CODE = 'SU') OR (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8500) OR  (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE = 8040) ) ) THEN 'Supermarket'
	WHEN BASE.STORE_CODE IN ('2223','2102','2101') THEN 'Department Store'
	WHEN BASE.STORE_CODE IN ('2013', '2012', '4004', '3009', '3010', '3011', '2001W', '3012') THEN 'Supermarket'
	WHEN BASE.STORE_CODE IN ('2005','2008','2010','2011','6001', '6002', '6003', '6004', '6005', '6012', '6009', '6010', '6011','6013') THEN 'Hypermarket'
	WHEN BASE.STORE_CODE IN ('3001', '3007', '4003', '3002', '3003', '3004', '3005', '3006') THEN 'Supermarket'
	ELSE BASE.STORE_FORMAT_DESC END AS STORE_FORMAT_DESC,
BASE.STORE_CODE, 
UPPER(BASE.STORE_DESCRIPTION) AS STORE_DESCRIPTION,
CASE WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 9000) THEN 'Z_OT'
     WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8500) THEN 'SU'
     WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE = 8040) THEN 'SU'
     WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE != 8040) THEN 'DS'
ELSE BASE.MERCH_GROUP_CODE END AS MERCH_GROUP_CODE,
CASE WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 9000) THEN 'OTHERS'
     WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8500) THEN 'SUPERMARKET'
     WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE = 8040) THEN 'SUPERMARKET'
     WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE != 8040) THEN 'DEPARTMENT STORE'
ELSE BASE.MERCH_GROUP_DESC END AS MERCH_GROUP_DESC,
BASE.GROUP_CODE,
BASE.GROUP_DESC,
BASE.DIVISION,
BASE.DIVISION_DESC,
BASE.DEPARTMENT_CODE, 
BASE.DEPARTMENT_DESC, 
BASE.NEW_FLG, 
BASE.MATURED_FLG,
SUM(WTD.TARGET_SALE_VAL) TARGET_SALE_VAL,
SUM(NET_SALE_OTR_TY) NET_SALE_OTR_TY, SUM(SALE_TOT_QTY_OTR_TY) SALE_TOT_QTY_OTR_TY, SUM(NET_SALE_CON_TY) NET_SALE_CON_TY, SUM(SALE_TOT_QTY_CON_TY) SALE_TOT_QTY_CON_TY, 
SUM(NET_SALE_OTR_LY) NET_SALE_OTR_LY, SUM(SALE_TOT_QTY_OTR_LY) SALE_TOT_QTY_OTR_LY, SUM(NET_SALE_CON_LY) NET_SALE_CON_LY, SUM(SALE_TOT_QTY_CON_LY) SALE_TOT_QTY_CON_LY
, SUM(NVL(WTD.TARGET_SALE_VAL,0)+NVL(NET_SALE_OTR_TY,0)+NVL(SALE_TOT_QTY_OTR_TY,0)+NVL(NET_SALE_CON_TY,0)+NVL(SALE_TOT_QTY_CON_TY,0)+NVL(NET_SALE_OTR_LY,0)+NVL(SALE_TOT_QTY_OTR_LY,0)+NVL(NET_SALE_CON_LY,0)+NVL(SALE_TOT_QTY_CON_LY,0)) SALE_CHECK
FROM

(SELECT D.MONTH_IN_YEAR, D.PER, S.STORE_KEY, S.STORE_FORMAT, S.STORE_FORMAT_DESC, 
	CASE WHEN S.STORE_CODE IN ('4002') THEN '2001W'
		ELSE S.STORE_CODE END AS STORE_CODE,
		UPPER(S.STORE_DESCRIPTION) AS STORE_DESCRIPTION, 
	M.MERCH_GROUP_CODE, M.MERCH_GROUP_DESC, M.GROUP_CODE, M.GROUP_DESC, M.DIVISION, M.DIVISION_DESC, M.DEPARTMENT_CODE, M.DEPARTMENT_DESC,S.NEW_FLG, S.MATURED_FLG
FROM
	(SELECT MONTH_IN_YEAR, TO_CHAR(DATE_FLD, 'MON' ) PER
			FROM DIM_DATE_PRL 
			WHERE DATE_KEY BETWEEN $yr_st_date_key AND $mo_en_date_key
	GROUP BY MONTH_IN_YEAR, TO_CHAR(DATE_FLD, 'MON' ))D,
	(SELECT DIM.STORE_KEY, DIM.STORE_FORMAT, DIM.STORE_FORMAT_DESC, DIM.STORE_CODE, DIM.STORE_DESCRIPTION, TST.NEW_FLG, TST.MATURED_FLG 
FROM DIM_STORE DIM
  LEFT JOIN (SELECT A.STORE_CODE, A.NEW_FLG, A.MATURED_FLG 
            FROM DIM_STORE A INNER JOIN (SELECT STORE_CODE, MAX(STORE_KEY) STORE_KEY FROM DIM_STORE GROUP BY STORE_CODE)B ON A.STORE_KEY = B.STORE_KEY AND A.STORE_CODE = B.STORE_CODE
            GROUP BY A.STORE_CODE, A.NEW_FLG, A.MATURED_FLG)TST ON DIM.STORE_CODE = TST.STORE_CODE
WHERE DIM.ACTIVE = 1 AND DIM.STORE_FORMAT IN (1, 2, 3, 4, 5) AND DIM.STORE_CODE NOT IN (6008))S,
	(SELECT D.MERCH_GROUP_CODE, D.MERCH_GROUP_DESC, D.GROUP_CODE, D.GROUP_DESC, D.DIVISION, D.DIVISION_DESC, D.DEPARTMENT_CODE, D.DEPARTMENT_DESC 
		FROM DIM_MERCHANDISE M 
			JOIN DIM_SUB_DEPT D ON M.MERCH_GROUP_CODE = D.MERCH_GROUP_CODE AND M.GROUP_CODE = D.GROUP_CODE AND M.GROUP2_CODE = D.GROUP2_CODE 
								AND M.DIVISION = D.DIVISION AND M.DEPARTMENT_CODE = D.DEPARTMENT_CODE AND M.SUB_DEPARTMENT_CODE = D.SUB_DEPARTMENT_CODE
		WHERE D.DIVISION NOT IN (4000))M
GROUP BY D.MONTH_IN_YEAR, D.PER, S.STORE_KEY, S.STORE_FORMAT, S.STORE_FORMAT_DESC, 
	CASE WHEN S.STORE_CODE IN ('4002') THEN '2001W'
		ELSE S.STORE_CODE END,
		UPPER(S.STORE_DESCRIPTION), 
	M.MERCH_GROUP_CODE, M.MERCH_GROUP_DESC, M.GROUP_CODE, M.GROUP_DESC, M.DIVISION, M.DIVISION_DESC, M.DEPARTMENT_CODE, M.DEPARTMENT_DESC,S.NEW_FLG, S.MATURED_FLG)BASE
	
LEFT JOIN

(SELECT 
AGG_MLY_STR_DEPT_TARGET.PER, 
DIM_STORE.STORE_KEY, 
DIM_STORE.STORE_FORMAT, 
CASE WHEN DIM_STORE.STORE_CODE IN ('4002') THEN '2001W'
	ELSE DIM_STORE.STORE_CODE END AS STORE_CODE,
DIM_SUB_DEPT.MERCH_GROUP_CODE,
DIM_SUB_DEPT.GROUP_CODE,
DIM_SUB_DEPT.DIVISION,
DIM_SUB_DEPT.DEPARTMENT_CODE,
NVL((SUM(TARGET_SALE_VAL))/1000,0) TARGET_SALE_VAL,  
NVL((SUM((NVL(SALE_NET_VAL_OTR_TY,0))-(NVL(SALE_TOT_TAX_VAL_OTR_TY,0))-(NVL(SALE_TOT_DISC_VAL_OTR_TY,0))))/1000,0) NET_SALE_OTR_TY,
SUM(SALE_TOT_QTY_OTR_TY)/1000 SALE_TOT_QTY_OTR_TY, 
NVL((SUM((NVL(SALE_NET_VAL_CON_TY,0))-(NVL(SALE_TOT_TAX_VAL_CON_TY,0))-(NVL(SALE_TOT_DISC_VAL_CON_TY,0))))/1000,0) NET_SALE_CON_TY,
SUM(SALE_TOT_QTY_CON_TY)/1000 SALE_TOT_QTY_CON_TY, 
NVL((SUM((NVL(SALE_NET_VAL_OTR_LY,0))-(NVL(SALE_TOT_TAX_VAL_OTR_LY,0))-(NVL(SALE_TOT_DISC_VAL_OTR_LY,0))))/1000,0) NET_SALE_OTR_LY,
SUM(SALE_TOT_QTY_OTR_LY)/1000 SALE_TOT_QTY_OTR_LY, 
NVL((SUM((NVL(SALE_NET_VAL_CON_LY,0))-(NVL(SALE_TOT_TAX_VAL_CON_LY,0))-(NVL(SALE_TOT_DISC_VAL_CON_LY,0))))/1000,0) NET_SALE_CON_LY,
SUM(SALE_TOT_QTY_CON_LY)/1000 SALE_TOT_QTY_CON_LY
FROM (	
	SELECT TBL.PER, TBL.STORE_KEY STORE_KEY, TBL.DS_KEY DS_KEY, TBL.STORE_CODE STORE_CODE, 
		TY_OTR.SALE_NET_VAL_OTR_TY, TY_OTR.SALE_TOT_TAX_VAL_OTR_TY, TY_OTR.SALE_TOT_DISC_VAL_OTR_TY, TY_OTR.SALE_TOT_QTY_OTR_TY,
		TY_CON.SALE_NET_VAL_CON_TY, TY_CON.SALE_TOT_TAX_VAL_CON_TY, TY_CON.SALE_TOT_DISC_VAL_CON_TY, TY_CON.SALE_TOT_QTY_CON_TY, 
		LY_OTR.SALE_NET_VAL_OTR_LY, LY_OTR.SALE_TOT_TAX_VAL_OTR_LY, LY_OTR.SALE_TOT_DISC_VAL_OTR_LY, LY_OTR.SALE_TOT_QTY_OTR_LY,
		LY_CON.SALE_NET_VAL_CON_LY, LY_CON.SALE_TOT_TAX_VAL_CON_LY, LY_CON.SALE_TOT_DISC_VAL_CON_LY, LY_CON.SALE_TOT_QTY_CON_LY,
		0 AS TARGET_SALE_VAL, 0 AS TARGET_SALE_VAL_LY, 0 AS TARGET_SALE_VAT, 0 AS TARGET_SALE_VAT_LY 
	FROM
		(SELECT D.PER, S.STORE_KEY, S.STORE_CODE, M.DS_KEY
		FROM
			(SELECT TO_CHAR(DATE_FLD, 'MON' ) PER
			FROM DIM_DATE_PRL 
			WHERE DATE_KEY BETWEEN $yr_st_date_key AND $mo_en_date_key
			GROUP BY TO_CHAR(DATE_FLD, 'MON' ))D,
			(SELECT STORE_KEY, STORE_CODE
			FROM DIM_STORE 
			WHERE ACTIVE = 1 AND STORE_FORMAT IN (1, 2, 3, 4, 5))S,
			(SELECT D.DS_KEY, D.MERCH_GROUP_CODE, D.MERCH_GROUP_DESC, D.GROUP_CODE, D.GROUP_DESC, D.DIVISION, D.DIVISION_DESC, D.DEPARTMENT_CODE, D.DEPARTMENT_DESC
			FROM DIM_MERCHANDISE M 
				JOIN DIM_SUB_DEPT D ON M.MERCH_GROUP_CODE = D.MERCH_GROUP_CODE AND M.GROUP_CODE = D.GROUP_CODE AND M.GROUP2_CODE = D.GROUP2_CODE AND M.DIVISION = D.DIVISION 
					AND M.DEPARTMENT_CODE = D.DEPARTMENT_CODE AND M.SUB_DEPARTMENT_CODE = D.SUB_DEPARTMENT_CODE )M
		GROUP BY D.PER, S.STORE_KEY, S.STORE_CODE, M.DS_KEY)TBL
		LEFT JOIN
		
		(SELECT TO_CHAR(DA.DATE_FLD, 'MON') PER, 
		STORE_KEY, DS_KEY, CAST(STORE_CODE AS VARCHAR2(20)) AS STORE_CODE, SUM(SALE_TOT_QTY) SALE_TOT_QTY_OTR_TY,
		SUM(SALE_NET_VAL) AS SALE_NET_VAL_OTR_TY, 
		SUM(SALE_TOT_TAX_VAL) SALE_TOT_TAX_VAL_OTR_TY, 
		SUM(SALE_TOT_DISC_VAL) SALE_TOT_DISC_VAL_OTR_TY
		FROM AGG_DLY_STR_PROD AGG 
			INNER JOIN DIM_PRODUCT M ON AGG.PRODUCT_KEY = M.PRODUCT_KEY AND (M.PRODUCT_CATEGORY = 0 OR M.PRODUCT_CATEGORY IS NULL)
			INNER JOIN DIM_SUB_DEPT D ON M.MERCH_GROUP_CODE = D.MERCH_GROUP_CODE AND M.GROUP_CODE = D.GROUP_CODE AND M.GROUP2_CODE = D.GROUP2_CODE AND M.DIVISION = D.DIVISION AND M.DEPARTMENT_CODE = D.DEPARTMENT_CODE AND M.SUB_DEPARTMENT_CODE = D.SUB_DEPARTMENT_CODE
			INNER JOIN DIM_DATE DA ON AGG.DATE_KEY = DA.DATE_KEY
		WHERE AGG.DATE_KEY BETWEEN $yr_st_date_key AND $mo_en_date_key
		GROUP BY TO_CHAR(DA.DATE_FLD, 'MON'), STORE_KEY, DS_KEY, STORE_CODE)TY_OTR
		
		ON TBL.PER = TY_OTR.PER AND TBL.STORE_KEY = TY_OTR.STORE_KEY AND TBL.STORE_CODE = TY_OTR.STORE_CODE AND TBL.DS_KEY = TY_OTR.DS_KEY
		LEFT JOIN
		
		(SELECT TO_CHAR(DA.DATE_FLD, 'MON') PER, 
		STORE_KEY, DS_KEY, CAST(STORE_CODE AS VARCHAR2(20)) AS STORE_CODE, SUM(SALE_TOT_QTY) SALE_TOT_QTY_CON_TY,  
		SUM(SALE_NET_VAL) AS SALE_NET_VAL_CON_TY, 
		SUM(SALE_TOT_TAX_VAL) SALE_TOT_TAX_VAL_CON_TY, 
		SUM(SALE_TOT_DISC_VAL) SALE_TOT_DISC_VAL_CON_TY
		FROM AGG_DLY_STR_PROD AGG 
			INNER JOIN DIM_PRODUCT M ON AGG.PRODUCT_KEY = M.PRODUCT_KEY AND M.PRODUCT_CATEGORY = 2
			INNER JOIN DIM_SUB_DEPT D ON M.MERCH_GROUP_CODE = D.MERCH_GROUP_CODE AND M.GROUP_CODE = D.GROUP_CODE AND M.GROUP2_CODE = D.GROUP2_CODE AND M.DIVISION = D.DIVISION AND M.DEPARTMENT_CODE = D.DEPARTMENT_CODE AND M.SUB_DEPARTMENT_CODE = D.SUB_DEPARTMENT_CODE
			INNER JOIN DIM_DATE DA ON AGG.DATE_KEY = DA.DATE_KEY
		WHERE AGG.DATE_KEY BETWEEN $yr_st_date_key AND $mo_en_date_key
		GROUP BY TO_CHAR(DA.DATE_FLD, 'MON'), STORE_KEY, DS_KEY, STORE_CODE)TY_CON
		
		ON TBL.PER = TY_CON.PER AND TBL.STORE_KEY = TY_CON.STORE_KEY AND TBL.STORE_CODE = TY_CON.STORE_CODE AND TBL.DS_KEY = TY_CON.DS_KEY
		LEFT JOIN
		
		(SELECT TO_CHAR(DA.DATE_FLD, 'MON') PER, 
		STORE_KEY, DS_KEY, CAST(STORE_CODE AS VARCHAR2(20)) AS STORE_CODE, SUM(SALE_TOT_QTY) SALE_TOT_QTY_OTR_LY,  
		SUM(SALE_NET_VAL) AS SALE_NET_VAL_OTR_LY, 
		SUM(SALE_TOT_TAX_VAL) SALE_TOT_TAX_VAL_OTR_LY, 
		SUM(SALE_TOT_DISC_VAL) SALE_TOT_DISC_VAL_OTR_LY
		FROM AGG_DLY_STR_PROD AGG 
			INNER JOIN DIM_PRODUCT M ON AGG.PRODUCT_KEY = M.PRODUCT_KEY AND (M.PRODUCT_CATEGORY = 0 OR M.PRODUCT_CATEGORY IS NULL)
			INNER JOIN DIM_SUB_DEPT D ON M.MERCH_GROUP_CODE = D.MERCH_GROUP_CODE AND M.GROUP_CODE = D.GROUP_CODE AND M.GROUP2_CODE = D.GROUP2_CODE AND M.DIVISION = D.DIVISION AND M.DEPARTMENT_CODE = D.DEPARTMENT_CODE AND M.SUB_DEPARTMENT_CODE = D.SUB_DEPARTMENT_CODE
			INNER JOIN DIM_DATE DA ON AGG.DATE_KEY = DA.DATE_KEY
		WHERE AGG.DATE_KEY BETWEEN $yr_st_date_key_ly AND $mo_en_date_key_ly
		GROUP BY TO_CHAR(DA.DATE_FLD, 'MON'), STORE_KEY, DS_KEY, STORE_CODE)LY_OTR
		
		ON TBL.PER = LY_OTR.PER AND TBL.STORE_KEY = LY_OTR.STORE_KEY AND TBL.STORE_CODE = LY_OTR.STORE_CODE AND TBL.DS_KEY = LY_OTR.DS_KEY
		LEFT JOIN
		
		(SELECT TO_CHAR(DA.DATE_FLD, 'MON') PER, 
		STORE_KEY, DS_KEY, CAST(STORE_CODE AS VARCHAR2(20)) AS STORE_CODE, SUM(SALE_TOT_QTY) SALE_TOT_QTY_CON_LY,  
		SUM(SALE_NET_VAL) AS SALE_NET_VAL_CON_LY, 
		SUM(SALE_TOT_TAX_VAL) SALE_TOT_TAX_VAL_CON_LY, 
		SUM(SALE_TOT_DISC_VAL) SALE_TOT_DISC_VAL_CON_LY
		FROM AGG_DLY_STR_PROD AGG 
			INNER JOIN DIM_PRODUCT M ON AGG.PRODUCT_KEY = M.PRODUCT_KEY AND M.PRODUCT_CATEGORY = 2 
			INNER JOIN DIM_SUB_DEPT D ON M.MERCH_GROUP_CODE = D.MERCH_GROUP_CODE AND M.GROUP_CODE = D.GROUP_CODE AND M.GROUP2_CODE = D.GROUP2_CODE AND M.DIVISION = D.DIVISION AND M.DEPARTMENT_CODE = D.DEPARTMENT_CODE AND M.SUB_DEPARTMENT_CODE = D.SUB_DEPARTMENT_CODE
			INNER JOIN DIM_DATE DA ON AGG.DATE_KEY = DA.DATE_KEY
		WHERE AGG.DATE_KEY BETWEEN $yr_st_date_key_ly AND $mo_en_date_key_ly
		GROUP BY TO_CHAR(DA.DATE_FLD, 'MON'), STORE_KEY, DS_KEY, STORE_CODE)LY_CON
		
		ON TBL.PER = LY_CON.PER AND TBL.STORE_KEY = LY_CON.STORE_KEY AND TBL.STORE_CODE = LY_CON.STORE_CODE AND TBL.DS_KEY = LY_CON.DS_KEY
	
	UNION ALL 
	
	SELECT TO_CHAR(DP.DATE_FLD, 'MON') PER, STORE_KEY, DS_KEY, CAST(STORE_CODE AS VARCHAR2(20)) AS STORE_CODE, 
		0 AS SALE_NET_VAL_OTR_TY, 0 AS SALE_TOT_TAX_VAL_OTR_TY, 0 AS SALE_TOT_DISC_VAL_OTR_TY, 0 AS SALE_TOT_QTY_OTR_TY,
		0 AS SALE_NET_VAL_OTR_LY, 0 AS SALE_TOT_TAX_VAL_OTR_LY, 0 AS SALE_TOT_DISC_VAL_OTR_LY, 0 AS SALE_TOT_QTY_CON_TY, 
		0 AS SALE_NET_VAL_CON_TY, 0 AS SALE_TOT_TAX_VAL_CON_TY, 0 AS SALE_TOT_DISC_VAL_CON_LY, 0 AS SALE_TOT_QTY_OTR_LY,
		0 AS SALE_NET_VAL_CON_LY, 0 AS SALE_TOT_TAX_VAL_CON_LY, 0 AS SALE_TOT_DISC_VAL_CON_LY, 0 AS SALE_TOT_QTY_CON_LY,		
		SUM (TARGET_SALE_VAL) AS TARGET_SALE_VAL, 
		SUM (TARGET_SALE_VAL_LY) AS TARGET_SALE_VAL_LY, 
		SUM (TARGET_SALE_VAT) AS TARGET_SALE_VAT, 
		SUM (TARGET_SALE_VAT_LY) AS TARGET_SALE_VAT_LY 
	FROM FCT_TARGET A JOIN DIM_DATE_PRL DP ON A.DATE_KEY = DP.DATE_KEY 
	WHERE A.DATE_KEY BETWEEN $yr_st_date_key AND $mo_en_date_key
	GROUP BY TO_CHAR(DP.DATE_FLD, 'MON'), STORE_KEY, STORE_CODE, DS_KEY 		
		
		) AGG_MLY_STR_DEPT_TARGET,DIM_STORE,DIM_SUB_DEPT
WHERE DIM_STORE.ACTIVE = 1 AND DIM_STORE.STORE_FORMAT IN (1, 2, 3, 4, 5) AND AGG_MLY_STR_DEPT_TARGET.STORE_KEY=DIM_STORE.STORE_KEY AND AGG_MLY_STR_DEPT_TARGET.DS_KEY=DIM_SUB_DEPT.DS_KEY
GROUP BY 
	AGG_MLY_STR_DEPT_TARGET.PER, 
	DIM_STORE.STORE_KEY, DIM_STORE.STORE_FORMAT, 
	CASE WHEN DIM_STORE.STORE_CODE IN ('4002') THEN '2001W'
		ELSE DIM_STORE.STORE_CODE END, 
	DIM_SUB_DEPT.MERCH_GROUP_CODE, DIM_SUB_DEPT.GROUP_CODE, DIM_SUB_DEPT.DIVISION, DIM_SUB_DEPT.DEPARTMENT_CODE
)WTD

ON BASE.PER = WTD.PER AND BASE.STORE_KEY = WTD.STORE_KEY AND BASE.STORE_FORMAT = WTD.STORE_FORMAT AND BASE.STORE_CODE = WTD.STORE_CODE AND BASE.MERCH_GROUP_CODE = WTD.MERCH_GROUP_CODE AND BASE.GROUP_CODE = WTD.GROUP_CODE AND BASE.DIVISION = WTD.DIVISION AND BASE.DEPARTMENT_CODE = WTD.DEPARTMENT_CODE

GROUP BY
BASE.MONTH_IN_YEAR, 
BASE.PER,
CASE 
	WHEN (BASE.STORE_CODE IN ('2001', '2002', '2003', '2004', '2006', '2007', '2009') AND ( (BASE.MERCH_GROUP_CODE = 'DS') OR (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 9000) OR  (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE != 8040) ) ) THEN '1'
	WHEN (BASE.STORE_CODE IN ('2001', '2002', '2003', '2004', '2006', '2007', '2009') AND ( (BASE.MERCH_GROUP_CODE = 'SU') OR (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8500) OR  (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE = 8040) ) ) THEN '2'
	WHEN BASE.STORE_CODE IN ('2223','2102','2101') THEN '1'
	WHEN BASE.STORE_CODE IN ('2013', '2012', '4004', '3009', '3010', '3011', '2001W', '3012') THEN '2'
	WHEN BASE.STORE_CODE IN ('2005','2008','2010','2011','6001', '6002', '6003', '6004', '6005', '6012', '6009', '6010', '6011','6013') THEN '4'
	WHEN BASE.STORE_CODE IN ('3001', '3007', '4003', '3002', '3003', '3004', '3005', '3006') THEN '2'
	ELSE BASE.STORE_FORMAT END, 
CASE 
	WHEN (BASE.STORE_CODE IN ('2001', '2002', '2003', '2004', '2006', '2007', '2009') AND ( (BASE.MERCH_GROUP_CODE = 'DS') OR (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 9000) OR  (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE != 8040) ) ) THEN 'Department Store'
	WHEN (BASE.STORE_CODE IN ('2001', '2002', '2003', '2004', '2006', '2007', '2009') AND ( (BASE.MERCH_GROUP_CODE = 'SU') OR (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8500) OR  (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE = 8040) ) ) THEN 'Supermarket'
	WHEN BASE.STORE_CODE IN ('2223','2102','2101') THEN 'Department Store'
	WHEN BASE.STORE_CODE IN ('2013', '2012', '4004', '3009', '3010', '3011', '2001W', '3012') THEN 'Supermarket'
	WHEN BASE.STORE_CODE IN ('2005','2008','2010','2011','6001', '6002', '6003', '6004', '6005', '6012', '6009', '6010', '6011','6013') THEN 'Hypermarket'
	WHEN BASE.STORE_CODE IN ('3001', '3007', '4003', '3002', '3003', '3004', '3005', '3006') THEN 'Supermarket'
	ELSE BASE.STORE_FORMAT_DESC END,
BASE.STORE_CODE, 
UPPER(BASE.STORE_DESCRIPTION),
CASE WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 9000) THEN 'Z_OT'
     WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8500) THEN 'SU'
     WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE = 8040) THEN 'SU'
     WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE != 8040) THEN 'DS'
ELSE BASE.MERCH_GROUP_CODE END,
CASE WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 9000) THEN 'OTHERS'
     WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8500) THEN 'SUPERMARKET'
     WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE = 8040) THEN 'SUPERMARKET'
     WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE != 8040) THEN 'DEPARTMENT STORE'
ELSE BASE.MERCH_GROUP_DESC END,
BASE.GROUP_CODE, 
BASE.GROUP_DESC, 
BASE.DIVISION, 
BASE.DIVISION_DESC, 
BASE.DEPARTMENT_CODE, 
BASE.DEPARTMENT_DESC, 
BASE.NEW_FLG, 
BASE.MATURED_FLG
)
WHERE SALE_CHECK <> 0
); 
 
EXECUTE IMMEDIATE 'DELETE FROM METRO_IT_SALES_DEPT WHERE PER IN (''$upd_per1'', ''$upd_per2'')';

FORALL i in sales_dept_tab.first .. sales_dept_tab.last
	INSERT INTO METRO_IT_SALES_DEPT VALUES sales_dept_tab(i);

COMMIT;

END;

};

my $sth = $dbh->prepare ($test);
$sth->execute;
 
$sth->finish();
$dbh->commit;

print "Done with Insert...";

}

sub generate_csv_sales_wtd {

print "Deleted old records from table METRO_IT_SALES_DEPT_WTD... \nPreparing to insert new data... \n";

$test = qq{ 
DECLARE
TYPE s_tab IS TABLE OF METRO_IT_SALES_DEPT_WTD%ROWTYPE;
sales_tab   s_tab := s_tab();
start_time  number;  
end_time   number;

BEGIN

SELECT * BULK COLLECT INTO sales_tab 
FROM 
(
SELECT 
STORE_FORMAT, 
STORE_FORMAT_DESC, 
STORE_CODE, STORE_DESCRIPTION, 
MERCH_GROUP_CODE, MERCH_GROUP_DESC, 
GROUP_CODE, GROUP_DESC, 
DIVISION, DIVISION_DESC, 
DEPARTMENT_CODE, DEPARTMENT_DESC, 
NEW_FLG, MATURED_FLG,
CASE WHEN SUM(TARGET_SALE_VAL) IS NULL THEN 0 ELSE SUM(TARGET_SALE_VAL) END AS TARGET_SALE_VAL, 
CASE WHEN SUM(SALE_TOT_QTY_OTR_TY) IS NULL THEN 0 ELSE SUM(SALE_TOT_QTY_OTR_TY) END AS SALE_TOT_QTY_OTR_TY, 
CASE WHEN SUM(NET_SALE_OTR_TY) IS NULL THEN 0 ELSE SUM(NET_SALE_OTR_TY) END AS NET_SALE_OTR_TY, 
CASE WHEN SUM(SALE_TOT_QTY_OTR_LY) IS NULL THEN 0 ELSE SUM(SALE_TOT_QTY_OTR_LY) END AS SALE_TOT_QTY_OTR_LY, 
CASE WHEN SUM(NET_SALE_OTR_LY) IS NULL THEN 0 ELSE SUM(NET_SALE_OTR_LY) END AS NET_SALE_OTR_LY, 
CASE WHEN SUM(SALE_TOT_QTY_CON_TY) IS NULL THEN 0 ELSE SUM(SALE_TOT_QTY_CON_TY) END AS SALE_TOT_QTY_CON_TY, 
CASE WHEN SUM(NET_SALE_CON_TY) IS NULL THEN 0 ELSE SUM(NET_SALE_CON_TY) END AS NET_SALE_CON_TY, 
CASE WHEN SUM(SALE_TOT_QTY_CON_LY) IS NULL THEN 0 ELSE SUM(SALE_TOT_QTY_CON_LY) END AS SALE_TOT_QTY_CON_LY, 
CASE WHEN SUM(NET_SALE_CON_LY) IS NULL THEN 0 ELSE SUM(NET_SALE_CON_LY) END AS NET_SALE_CON_LY,
SYSDATE AS UPDATE_DATE, WEEK_NO

FROM (
SELECT 
CASE 
	WHEN (BASE.STORE_CODE IN ('2001', '2002', '2003', '2004', '2006', '2007', '2009') AND ( (BASE.MERCH_GROUP_CODE = 'DS') OR (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 9000) OR  (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE != 8040) ) ) THEN '1'
	WHEN (BASE.STORE_CODE IN ('2001', '2002', '2003', '2004', '2006', '2007', '2009') AND ( (BASE.MERCH_GROUP_CODE = 'SU') OR (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8500) OR  (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE = 8040) ) ) THEN '2'
	WHEN BASE.STORE_CODE IN ('2223','2102','2101') THEN '1'
	WHEN BASE.STORE_CODE IN ('2013', '2012', '4004', '3009', '3010', '3011', '2001W', '3012') THEN '2'
	WHEN BASE.STORE_CODE IN ('2005','2008','2010','2011','6001', '6002', '6003', '6004', '6005', '6012', '6009', '6010', '6011','6013') THEN '4'
	WHEN BASE.STORE_CODE IN ('3001', '3007', '4003', '3002', '3003', '3004', '3005', '3006') THEN '2'
	ELSE BASE.STORE_FORMAT END AS STORE_FORMAT, 
CASE 
	WHEN (BASE.STORE_CODE IN ('2001', '2002', '2003', '2004', '2006', '2007', '2009') AND ( (BASE.MERCH_GROUP_CODE = 'DS') OR (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 9000) OR  (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE != 8040) ) ) THEN 'Department Store'
	WHEN (BASE.STORE_CODE IN ('2001', '2002', '2003', '2004', '2006', '2007', '2009') AND ( (BASE.MERCH_GROUP_CODE = 'SU') OR (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8500) OR  (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE = 8040) ) ) THEN 'Supermarket'
	WHEN BASE.STORE_CODE IN ('2223','2102','2101') THEN 'Department Store'
	WHEN BASE.STORE_CODE IN ('2013', '2012', '4004', '3009', '3010', '3011', '2001W', '3012') THEN 'Supermarket'
	WHEN BASE.STORE_CODE IN ('2005','2008','2010','2011','6001', '6002', '6003', '6004', '6005', '6012', '6009', '6010', '6011','6013') THEN 'Hypermarket'
	WHEN BASE.STORE_CODE IN ('3001', '3007', '4003', '3002', '3003', '3004', '3005', '3006') THEN 'Supermarket'
	ELSE BASE.STORE_FORMAT_DESC END AS STORE_FORMAT_DESC,
BASE.STORE_CODE, 
UPPER(BASE.STORE_DESCRIPTION) AS STORE_DESCRIPTION,
CASE WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 9000) THEN 'Z_OT'
     WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8500) THEN 'SU'
     WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE = 8040) THEN 'SU'
     WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE != 8040) THEN 'DS'
ELSE BASE.MERCH_GROUP_CODE END AS MERCH_GROUP_CODE,
CASE WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 9000) THEN 'OTHERS'
     WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8500) THEN 'SUPERMARKET'
     WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE = 8040) THEN 'SUPERMARKET'
     WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE != 8040) THEN 'DEPARTMENT STORE'
ELSE BASE.MERCH_GROUP_DESC END AS MERCH_GROUP_DESC,
BASE.GROUP_CODE,
BASE.GROUP_DESC,
BASE.DIVISION,
BASE.DIVISION_DESC,
BASE.DEPARTMENT_CODE, 
BASE.DEPARTMENT_DESC, 
BASE.NEW_FLG, 
BASE.MATURED_FLG, BASE.WEEK_NO, 
SUM(WTD.TARGET_SALE_VAL) TARGET_SALE_VAL,
SUM(NET_SALE_OTR_TY) NET_SALE_OTR_TY, SUM(SALE_TOT_QTY_OTR_TY) SALE_TOT_QTY_OTR_TY, SUM(NET_SALE_CON_TY) NET_SALE_CON_TY, SUM(SALE_TOT_QTY_CON_TY) SALE_TOT_QTY_CON_TY, 
SUM(NET_SALE_OTR_LY) NET_SALE_OTR_LY, SUM(SALE_TOT_QTY_OTR_LY) SALE_TOT_QTY_OTR_LY, SUM(NET_SALE_CON_LY) NET_SALE_CON_LY, SUM(SALE_TOT_QTY_CON_LY) SALE_TOT_QTY_CON_LY
, SUM(NVL(WTD.TARGET_SALE_VAL,0)+NVL(NET_SALE_OTR_TY,0)+NVL(SALE_TOT_QTY_OTR_TY,0)+NVL(NET_SALE_CON_TY,0)+NVL(SALE_TOT_QTY_CON_TY,0)+NVL(NET_SALE_OTR_LY,0)+NVL(SALE_TOT_QTY_OTR_LY,0)+NVL(NET_SALE_CON_LY,0)+NVL(SALE_TOT_QTY_CON_LY,0)) SALE_CHECK
FROM

(SELECT D.MONTH_IN_YEAR, D.WEEK_NO, D.PER, S.STORE_KEY, S.STORE_FORMAT, S.STORE_FORMAT_DESC, 
	CASE WHEN S.STORE_CODE IN ('4002') THEN '2001W'
		ELSE S.STORE_CODE END AS STORE_CODE,
		UPPER(S.STORE_DESCRIPTION) AS STORE_DESCRIPTION, 
	M.MERCH_GROUP_CODE, M.MERCH_GROUP_DESC, M.GROUP_CODE, M.GROUP_DESC, M.DIVISION, M.DIVISION_DESC, M.DEPARTMENT_CODE, M.DEPARTMENT_DESC,S.NEW_FLG, S.MATURED_FLG
FROM
	(SELECT MONTH_IN_YEAR, WEEK_NUMBER_THIS_YEAR WEEK_NO, TO_CHAR(DATE_FLD, 'MON' ) PER
			FROM DIM_DATE
			WHERE DATE_KEY BETWEEN $wk_st_date_key AND $wk_en_date_key
	GROUP BY MONTH_IN_YEAR, WEEK_NUMBER_THIS_YEAR, TO_CHAR(DATE_FLD, 'MON' ))D,
	(SELECT DIM.STORE_KEY, DIM.STORE_FORMAT, DIM.STORE_FORMAT_DESC, DIM.STORE_CODE, DIM.STORE_DESCRIPTION, TST.NEW_FLG, TST.MATURED_FLG 
FROM DIM_STORE DIM
  LEFT JOIN (SELECT A.STORE_CODE, A.NEW_FLG, A.MATURED_FLG 
            FROM DIM_STORE A INNER JOIN (SELECT STORE_CODE, MAX(STORE_KEY) STORE_KEY FROM DIM_STORE GROUP BY STORE_CODE)B ON A.STORE_KEY = B.STORE_KEY AND A.STORE_CODE = B.STORE_CODE
            GROUP BY A.STORE_CODE, A.NEW_FLG, A.MATURED_FLG)TST ON DIM.STORE_CODE = TST.STORE_CODE
WHERE DIM.ACTIVE = 1 AND DIM.STORE_FORMAT IN (1, 2, 3, 4, 5) AND DIM.STORE_CODE NOT IN (6008))S,
	(SELECT D.MERCH_GROUP_CODE, D.MERCH_GROUP_DESC, D.GROUP_CODE, D.GROUP_DESC, D.DIVISION, D.DIVISION_DESC, D.DEPARTMENT_CODE, D.DEPARTMENT_DESC 
		FROM DIM_MERCHANDISE M 
			JOIN DIM_SUB_DEPT D ON M.MERCH_GROUP_CODE = D.MERCH_GROUP_CODE AND M.GROUP_CODE = D.GROUP_CODE AND M.GROUP2_CODE = D.GROUP2_CODE 
								AND M.DIVISION = D.DIVISION AND M.DEPARTMENT_CODE = D.DEPARTMENT_CODE AND M.SUB_DEPARTMENT_CODE = D.SUB_DEPARTMENT_CODE
		WHERE D.DIVISION NOT IN (4000))M
GROUP BY D.MONTH_IN_YEAR, D.WEEK_NO, D.PER, S.STORE_KEY, S.STORE_FORMAT, S.STORE_FORMAT_DESC, 
	CASE WHEN S.STORE_CODE IN ('4002') THEN '2001W'
		ELSE S.STORE_CODE END,
		UPPER(S.STORE_DESCRIPTION), 
	M.MERCH_GROUP_CODE, M.MERCH_GROUP_DESC, M.GROUP_CODE, M.GROUP_DESC, M.DIVISION, M.DIVISION_DESC, M.DEPARTMENT_CODE, M.DEPARTMENT_DESC,S.NEW_FLG, S.MATURED_FLG)BASE
	
LEFT JOIN

(SELECT 
AGG_MLY_STR_DEPT_TARGET.PER, 
DIM_STORE.STORE_KEY, 
DIM_STORE.STORE_FORMAT, 
CASE WHEN DIM_STORE.STORE_CODE IN ('4002') THEN '2001W'
	ELSE DIM_STORE.STORE_CODE END AS STORE_CODE,
DIM_SUB_DEPT.MERCH_GROUP_CODE,
DIM_SUB_DEPT.GROUP_CODE,
DIM_SUB_DEPT.DIVISION,
DIM_SUB_DEPT.DEPARTMENT_CODE,
NVL((SUM(TARGET_SALE_VAL))/1000,0) TARGET_SALE_VAL,  
NVL((SUM((NVL(SALE_NET_VAL_OTR_TY,0))-(NVL(SALE_TOT_TAX_VAL_OTR_TY,0))-(NVL(SALE_TOT_DISC_VAL_OTR_TY,0))))/1000,0) NET_SALE_OTR_TY,
SUM(SALE_TOT_QTY_OTR_TY)/1000 SALE_TOT_QTY_OTR_TY, 
NVL((SUM((NVL(SALE_NET_VAL_CON_TY,0))-(NVL(SALE_TOT_TAX_VAL_CON_TY,0))-(NVL(SALE_TOT_DISC_VAL_CON_TY,0))))/1000,0) NET_SALE_CON_TY,
SUM(SALE_TOT_QTY_CON_TY)/1000 SALE_TOT_QTY_CON_TY, 
NVL((SUM((NVL(SALE_NET_VAL_OTR_LY,0))-(NVL(SALE_TOT_TAX_VAL_OTR_LY,0))-(NVL(SALE_TOT_DISC_VAL_OTR_LY,0))))/1000,0) NET_SALE_OTR_LY,
SUM(SALE_TOT_QTY_OTR_LY)/1000 SALE_TOT_QTY_OTR_LY, 
NVL((SUM((NVL(SALE_NET_VAL_CON_LY,0))-(NVL(SALE_TOT_TAX_VAL_CON_LY,0))-(NVL(SALE_TOT_DISC_VAL_CON_LY,0))))/1000,0) NET_SALE_CON_LY,
SUM(SALE_TOT_QTY_CON_LY)/1000 SALE_TOT_QTY_CON_LY
FROM (	
	SELECT TBL.PER, TBL.STORE_KEY STORE_KEY, TBL.DS_KEY DS_KEY, TBL.STORE_CODE STORE_CODE, 
		TY_OTR.SALE_NET_VAL_OTR_TY, TY_OTR.SALE_TOT_TAX_VAL_OTR_TY, TY_OTR.SALE_TOT_DISC_VAL_OTR_TY, TY_OTR.SALE_TOT_QTY_OTR_TY,
		TY_CON.SALE_NET_VAL_CON_TY, TY_CON.SALE_TOT_TAX_VAL_CON_TY, TY_CON.SALE_TOT_DISC_VAL_CON_TY, TY_CON.SALE_TOT_QTY_CON_TY, 
		LY_OTR.SALE_NET_VAL_OTR_LY, LY_OTR.SALE_TOT_TAX_VAL_OTR_LY, LY_OTR.SALE_TOT_DISC_VAL_OTR_LY, LY_OTR.SALE_TOT_QTY_OTR_LY,
		LY_CON.SALE_NET_VAL_CON_LY, LY_CON.SALE_TOT_TAX_VAL_CON_LY, LY_CON.SALE_TOT_DISC_VAL_CON_LY, LY_CON.SALE_TOT_QTY_CON_LY,
		0 AS TARGET_SALE_VAL, 0 AS TARGET_SALE_VAL_LY, 0 AS TARGET_SALE_VAT, 0 AS TARGET_SALE_VAT_LY 
	FROM
		(SELECT D.PER, S.STORE_KEY, S.STORE_CODE, M.DS_KEY
		FROM
			(SELECT TO_CHAR(DATE_FLD, 'MON' ) PER
			FROM DIM_DATE
			WHERE DATE_KEY BETWEEN $wk_st_date_key AND $wk_en_date_key
			GROUP BY TO_CHAR(DATE_FLD, 'MON' ))D,
			(SELECT STORE_KEY, STORE_CODE
			FROM DIM_STORE 
			WHERE ACTIVE = 1 AND STORE_FORMAT IN (1, 2, 3, 4, 5))S,
			(SELECT D.DS_KEY, D.MERCH_GROUP_CODE, D.MERCH_GROUP_DESC, D.GROUP_CODE, D.GROUP_DESC, D.DIVISION, D.DIVISION_DESC, D.DEPARTMENT_CODE, D.DEPARTMENT_DESC
			FROM DIM_MERCHANDISE M 
				JOIN DIM_SUB_DEPT D ON M.MERCH_GROUP_CODE = D.MERCH_GROUP_CODE AND M.GROUP_CODE = D.GROUP_CODE AND M.GROUP2_CODE = D.GROUP2_CODE AND M.DIVISION = D.DIVISION 
					AND M.DEPARTMENT_CODE = D.DEPARTMENT_CODE AND M.SUB_DEPARTMENT_CODE = D.SUB_DEPARTMENT_CODE )M
		GROUP BY D.PER, S.STORE_KEY, S.STORE_CODE, M.DS_KEY)TBL
		LEFT JOIN
		
		(SELECT TO_CHAR(DA.DATE_FLD, 'MON') PER, 
		STORE_KEY, DS_KEY, CAST(STORE_CODE AS VARCHAR2(20)) AS STORE_CODE, SUM(SALE_TOT_QTY) SALE_TOT_QTY_OTR_TY,
		SUM(SALE_NET_VAL) AS SALE_NET_VAL_OTR_TY, 
		SUM(SALE_TOT_TAX_VAL) SALE_TOT_TAX_VAL_OTR_TY, 
		SUM(SALE_TOT_DISC_VAL) SALE_TOT_DISC_VAL_OTR_TY
		FROM AGG_DLY_STR_PROD AGG 
			INNER JOIN DIM_PRODUCT M ON AGG.PRODUCT_KEY = M.PRODUCT_KEY AND (M.PRODUCT_CATEGORY = 0 OR M.PRODUCT_CATEGORY IS NULL)
			INNER JOIN DIM_SUB_DEPT D ON M.MERCH_GROUP_CODE = D.MERCH_GROUP_CODE AND M.GROUP_CODE = D.GROUP_CODE AND M.GROUP2_CODE = D.GROUP2_CODE AND M.DIVISION = D.DIVISION AND M.DEPARTMENT_CODE = D.DEPARTMENT_CODE AND M.SUB_DEPARTMENT_CODE = D.SUB_DEPARTMENT_CODE
			INNER JOIN DIM_DATE DA ON AGG.DATE_KEY = DA.DATE_KEY
		WHERE AGG.DATE_KEY BETWEEN $wk_st_date_key AND $wk_en_date_key 
		GROUP BY TO_CHAR(DA.DATE_FLD, 'MON'), STORE_KEY, DS_KEY, STORE_CODE)TY_OTR
		
		ON TBL.PER = TY_OTR.PER AND TBL.STORE_KEY = TY_OTR.STORE_KEY AND TBL.STORE_CODE = TY_OTR.STORE_CODE AND TBL.DS_KEY = TY_OTR.DS_KEY
		LEFT JOIN
		
		(SELECT TO_CHAR(DA.DATE_FLD, 'MON') PER, 
		STORE_KEY, DS_KEY, CAST(STORE_CODE AS VARCHAR2(20)) AS STORE_CODE, SUM(SALE_TOT_QTY) SALE_TOT_QTY_CON_TY,  
		SUM(SALE_NET_VAL) AS SALE_NET_VAL_CON_TY, 
		SUM(SALE_TOT_TAX_VAL) SALE_TOT_TAX_VAL_CON_TY, 
		SUM(SALE_TOT_DISC_VAL) SALE_TOT_DISC_VAL_CON_TY
		FROM AGG_DLY_STR_PROD AGG 
			INNER JOIN DIM_PRODUCT M ON AGG.PRODUCT_KEY = M.PRODUCT_KEY AND M.PRODUCT_CATEGORY = 2
			INNER JOIN DIM_SUB_DEPT D ON M.MERCH_GROUP_CODE = D.MERCH_GROUP_CODE AND M.GROUP_CODE = D.GROUP_CODE AND M.GROUP2_CODE = D.GROUP2_CODE AND M.DIVISION = D.DIVISION AND M.DEPARTMENT_CODE = D.DEPARTMENT_CODE AND M.SUB_DEPARTMENT_CODE = D.SUB_DEPARTMENT_CODE
			INNER JOIN DIM_DATE DA ON AGG.DATE_KEY = DA.DATE_KEY
		WHERE AGG.DATE_KEY BETWEEN $wk_st_date_key AND $wk_en_date_key 
		GROUP BY TO_CHAR(DA.DATE_FLD, 'MON'), STORE_KEY, DS_KEY, STORE_CODE)TY_CON
		
		ON TBL.PER = TY_CON.PER AND TBL.STORE_KEY = TY_CON.STORE_KEY AND TBL.STORE_CODE = TY_CON.STORE_CODE AND TBL.DS_KEY = TY_CON.DS_KEY
		LEFT JOIN
		
		(SELECT TO_CHAR(DA.DATE_FLD, 'MON') PER, 
		STORE_KEY, DS_KEY, CAST(STORE_CODE AS VARCHAR2(20)) AS STORE_CODE, SUM(SALE_TOT_QTY) SALE_TOT_QTY_OTR_LY,  
		SUM(SALE_NET_VAL) AS SALE_NET_VAL_OTR_LY, 
		SUM(SALE_TOT_TAX_VAL) SALE_TOT_TAX_VAL_OTR_LY, 
		SUM(SALE_TOT_DISC_VAL) SALE_TOT_DISC_VAL_OTR_LY
		FROM AGG_DLY_STR_PROD AGG 
			INNER JOIN DIM_PRODUCT M ON AGG.PRODUCT_KEY = M.PRODUCT_KEY AND (M.PRODUCT_CATEGORY = 0 OR M.PRODUCT_CATEGORY IS NULL)
			INNER JOIN DIM_SUB_DEPT D ON M.MERCH_GROUP_CODE = D.MERCH_GROUP_CODE AND M.GROUP_CODE = D.GROUP_CODE AND M.GROUP2_CODE = D.GROUP2_CODE AND M.DIVISION = D.DIVISION AND M.DEPARTMENT_CODE = D.DEPARTMENT_CODE AND M.SUB_DEPARTMENT_CODE = D.SUB_DEPARTMENT_CODE
			INNER JOIN DIM_DATE DA ON AGG.DATE_KEY = DA.DATE_KEY
		WHERE AGG.DATE_KEY BETWEEN $wk_st_date_key_ly AND $wk_en_date_key_ly 
		GROUP BY TO_CHAR(DA.DATE_FLD, 'MON'), STORE_KEY, DS_KEY, STORE_CODE)LY_OTR
		
		ON TBL.PER = LY_OTR.PER AND TBL.STORE_KEY = LY_OTR.STORE_KEY AND TBL.STORE_CODE = LY_OTR.STORE_CODE AND TBL.DS_KEY = LY_OTR.DS_KEY
		LEFT JOIN
		
		(SELECT TO_CHAR(DA.DATE_FLD, 'MON') PER, 
		STORE_KEY, DS_KEY, CAST(STORE_CODE AS VARCHAR2(20)) AS STORE_CODE, SUM(SALE_TOT_QTY) SALE_TOT_QTY_CON_LY,  
		SUM(SALE_NET_VAL) AS SALE_NET_VAL_CON_LY, 
		SUM(SALE_TOT_TAX_VAL) SALE_TOT_TAX_VAL_CON_LY, 
		SUM(SALE_TOT_DISC_VAL) SALE_TOT_DISC_VAL_CON_LY
		FROM AGG_DLY_STR_PROD AGG 
			INNER JOIN DIM_PRODUCT M ON AGG.PRODUCT_KEY = M.PRODUCT_KEY AND M.PRODUCT_CATEGORY = 2 
			INNER JOIN DIM_SUB_DEPT D ON M.MERCH_GROUP_CODE = D.MERCH_GROUP_CODE AND M.GROUP_CODE = D.GROUP_CODE AND M.GROUP2_CODE = D.GROUP2_CODE AND M.DIVISION = D.DIVISION AND M.DEPARTMENT_CODE = D.DEPARTMENT_CODE AND M.SUB_DEPARTMENT_CODE = D.SUB_DEPARTMENT_CODE
			INNER JOIN DIM_DATE DA ON AGG.DATE_KEY = DA.DATE_KEY
		WHERE AGG.DATE_KEY BETWEEN $wk_st_date_key_ly AND $wk_en_date_key_ly 
		GROUP BY TO_CHAR(DA.DATE_FLD, 'MON'), STORE_KEY, DS_KEY, STORE_CODE)LY_CON
		
		ON TBL.PER = LY_CON.PER AND TBL.STORE_KEY = LY_CON.STORE_KEY AND TBL.STORE_CODE = LY_CON.STORE_CODE AND TBL.DS_KEY = LY_CON.DS_KEY
	
	UNION ALL 
	
	SELECT TO_CHAR(DP.DATE_FLD, 'MON') PER, STORE_KEY, DS_KEY, CAST(STORE_CODE AS VARCHAR2(20)) AS STORE_CODE, 
		0 AS SALE_NET_VAL_OTR_TY, 0 AS SALE_TOT_TAX_VAL_OTR_TY, 0 AS SALE_TOT_DISC_VAL_OTR_TY, 0 AS SALE_TOT_QTY_OTR_TY,
		0 AS SALE_NET_VAL_OTR_LY, 0 AS SALE_TOT_TAX_VAL_OTR_LY, 0 AS SALE_TOT_DISC_VAL_OTR_LY, 0 AS SALE_TOT_QTY_CON_TY, 
		0 AS SALE_NET_VAL_CON_TY, 0 AS SALE_TOT_TAX_VAL_CON_TY, 0 AS SALE_TOT_DISC_VAL_CON_LY, 0 AS SALE_TOT_QTY_OTR_LY,
		0 AS SALE_NET_VAL_CON_LY, 0 AS SALE_TOT_TAX_VAL_CON_LY, 0 AS SALE_TOT_DISC_VAL_CON_LY, 0 AS SALE_TOT_QTY_CON_LY,		
		SUM (TARGET_SALE_VAL) AS TARGET_SALE_VAL, 
		SUM (TARGET_SALE_VAL_LY) AS TARGET_SALE_VAL_LY, 
		SUM (TARGET_SALE_VAT) AS TARGET_SALE_VAT, 
		SUM (TARGET_SALE_VAT_LY) AS TARGET_SALE_VAT_LY 
	FROM FCT_TARGET A JOIN DIM_DATE_PRL DP ON A.DATE_KEY = DP.DATE_KEY 
	WHERE A.DATE_KEY BETWEEN $wk_st_date_key AND $wk_en_date_key 
	GROUP BY TO_CHAR(DP.DATE_FLD, 'MON'), STORE_KEY, STORE_CODE, DS_KEY 		
		
		) AGG_MLY_STR_DEPT_TARGET,DIM_STORE,DIM_SUB_DEPT
WHERE DIM_STORE.ACTIVE = 1 AND DIM_STORE.STORE_FORMAT IN (1, 2, 3, 4, 5) AND AGG_MLY_STR_DEPT_TARGET.STORE_KEY=DIM_STORE.STORE_KEY AND AGG_MLY_STR_DEPT_TARGET.DS_KEY=DIM_SUB_DEPT.DS_KEY
GROUP BY 
	AGG_MLY_STR_DEPT_TARGET.PER, 
	DIM_STORE.STORE_KEY, DIM_STORE.STORE_FORMAT, 
	CASE WHEN DIM_STORE.STORE_CODE IN ('4002') THEN '2001W'
		ELSE DIM_STORE.STORE_CODE END, 
	DIM_SUB_DEPT.MERCH_GROUP_CODE, DIM_SUB_DEPT.GROUP_CODE, DIM_SUB_DEPT.DIVISION, DIM_SUB_DEPT.DEPARTMENT_CODE
)WTD

ON BASE.PER = WTD.PER AND BASE.STORE_KEY = WTD.STORE_KEY AND BASE.STORE_FORMAT = WTD.STORE_FORMAT AND BASE.STORE_CODE = WTD.STORE_CODE AND BASE.MERCH_GROUP_CODE = WTD.MERCH_GROUP_CODE AND BASE.GROUP_CODE = WTD.GROUP_CODE AND BASE.DIVISION = WTD.DIVISION AND BASE.DEPARTMENT_CODE = WTD.DEPARTMENT_CODE

GROUP BY
CASE 
	WHEN (BASE.STORE_CODE IN ('2001', '2002', '2003', '2004', '2006', '2007', '2009') AND ( (BASE.MERCH_GROUP_CODE = 'DS') OR (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 9000) OR  (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE != 8040) ) ) THEN '1'
	WHEN (BASE.STORE_CODE IN ('2001', '2002', '2003', '2004', '2006', '2007', '2009') AND ( (BASE.MERCH_GROUP_CODE = 'SU') OR (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8500) OR  (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE = 8040) ) ) THEN '2'
	WHEN BASE.STORE_CODE IN ('2223','2102','2101') THEN '1'
	WHEN BASE.STORE_CODE IN ('2013', '2012', '4004', '3009', '3010', '3011', '2001W', '3012') THEN '2'
	WHEN BASE.STORE_CODE IN ('2005','2008','2010','2011','6001', '6002', '6003', '6004', '6005', '6012', '6009', '6010', '6011','6013') THEN '4'
	WHEN BASE.STORE_CODE IN ('3001', '3007', '4003', '3002', '3003', '3004', '3005', '3006') THEN '2'
	ELSE BASE.STORE_FORMAT END, 
CASE 
	WHEN (BASE.STORE_CODE IN ('2001', '2002', '2003', '2004', '2006', '2007', '2009') AND ( (BASE.MERCH_GROUP_CODE = 'DS') OR (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 9000) OR  (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE != 8040) ) ) THEN 'Department Store'
	WHEN (BASE.STORE_CODE IN ('2001', '2002', '2003', '2004', '2006', '2007', '2009') AND ( (BASE.MERCH_GROUP_CODE = 'SU') OR (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8500) OR  (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE = 8040) ) ) THEN 'Supermarket'
	WHEN BASE.STORE_CODE IN ('2223','2102','2101') THEN 'Department Store'
	WHEN BASE.STORE_CODE IN ('2013', '2012', '4004', '3009', '3010', '3011', '2001W', '3012') THEN 'Supermarket'
	WHEN BASE.STORE_CODE IN ('2005','2008','2010','2011','6001', '6002', '6003', '6004', '6005', '6012', '6009', '6010', '6011','6013') THEN 'Hypermarket'
	WHEN BASE.STORE_CODE IN ('3001', '3007', '4003', '3002', '3003', '3004', '3005', '3006') THEN 'Supermarket'
	ELSE BASE.STORE_FORMAT_DESC END, 
BASE.STORE_CODE, 
UPPER(BASE.STORE_DESCRIPTION),
CASE WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 9000) THEN 'Z_OT'
     WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8500) THEN 'SU'
     WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE = 8040) THEN 'SU'
     WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE != 8040) THEN 'DS'
ELSE BASE.MERCH_GROUP_CODE END,
CASE WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 9000) THEN 'OTHERS'
     WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8500) THEN 'SUPERMARKET'
     WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE = 8040) THEN 'SUPERMARKET'
     WHEN (BASE.MERCH_GROUP_CODE = 'OT' AND BASE.DIVISION = 8000 AND BASE.DEPARTMENT_CODE != 8040) THEN 'DEPARTMENT STORE'
ELSE BASE.MERCH_GROUP_DESC END,
BASE.GROUP_CODE, 
BASE.GROUP_DESC, 
BASE.DIVISION, 
BASE.DIVISION_DESC, 
BASE.DEPARTMENT_CODE, 
BASE.DEPARTMENT_DESC, 
BASE.NEW_FLG, 
BASE.MATURED_FLG, BASE.WEEK_NO
)
WHERE SALE_CHECK <> 0
GROUP BY 
STORE_FORMAT, 
STORE_FORMAT_DESC, 
STORE_CODE, STORE_DESCRIPTION, MERCH_GROUP_CODE, MERCH_GROUP_DESC, GROUP_CODE, GROUP_DESC, DIVISION, DIVISION_DESC, DEPARTMENT_CODE, DEPARTMENT_DESC, 
NEW_FLG, 
MATURED_FLG, WEEK_NO
); 
 
--EXECUTE IMMEDIATE 'DELETE FROM METRO_IT_SALES_DEPT_WTD WHERE WEEK_NO = $wk_number-4';
EXECUTE IMMEDIATE 'TRUNCATE TABLE METRO_IT_SALES_DEPT_WTD';
start_time := DBMS_UTILITY.get_time;
FORALL i in sales_tab.first .. sales_tab.last
	INSERT INTO METRO_IT_SALES_DEPT_WTD VALUES sales_tab(i);
end_time := DBMS_UTILITY.get_time;
--DBMS_OUTPUT.PUT_LINE(‘Bulk Insert: ’||to_char(end_time-start_time));
COMMIT;
END;

};

my $sth = $dbh->prepare ($test);
$sth->execute;
 
$sth->finish();
$dbh->commit;

print "Done with Insert...";

}

sub generate_instock {

print "Done Deleting current periods records on table METRO_IT_INSTOCK_DEPT... \nPreparing to Insert... \n";

$test = '
DECLARE
TYPE inst_tab IS TABLE OF METRO_IT_INSTOCK_DEPT%ROWTYPE;
instock_tab   inst_tab := inst_tab();

BEGIN

SELECT * BULK COLLECT INTO instock_tab 
FROM 
(
SELECT
CASE 
	WHEN (SGD.STORE IN (\'2001\', \'2002\', \'2003\', \'2004\', \'2006\', \'2007\', \'2009\') AND ( (SGD.MERCH_GROUP_CODE = \'DS\') OR (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 9000) OR  (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 8000 AND SGD.GROUP_NO != 8040) ) ) THEN \'1\'
	WHEN (SGD.STORE IN (\'2001\', \'2002\', \'2003\', \'2004\', \'2006\', \'2007\', \'2009\') AND ( (SGD.MERCH_GROUP_CODE = \'SU\') OR (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 8500) OR  (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 8000 AND SGD.GROUP_NO = 8040) ) ) THEN \'2\'
	WHEN SGD.STORE IN (\'2223\') THEN \'1\'
	WHEN SGD.STORE IN (\'2013\', \'2012\', \'4004\', \'3009\', \'3010\', \'3011\', \'4002\', \'3012\') THEN \'2\'
	WHEN SGD.STORE IN (\'2005\',\'2008\',\'2010\',\'2011\',\'6001\', \'6002\', \'6003\', \'6004\', \'6005\', \'6012\', \'6009\', \'6010\', \'6011\') THEN \'4\'
	WHEN SGD.STORE IN (\'3001\', \'3007\', \'4003\', \'3002\', \'3003\', \'3004\', \'3005\', \'3006\') THEN \'2\'
	ELSE TO_CHAR(SGD.STORE_FORMAT) END AS STORE_FORMAT, 
CASE 
	WHEN (SGD.STORE IN (\'2001\', \'2002\', \'2003\', \'2004\', \'2006\', \'2007\', \'2009\') AND ( (SGD.MERCH_GROUP_CODE = \'DS\') OR (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 9000) OR  (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 8000 AND SGD.GROUP_NO != 8040) ) ) THEN \'Department Store\'
	WHEN (SGD.STORE IN (\'2001\', \'2002\', \'2003\', \'2004\', \'2006\', \'2007\', \'2009\') AND ( (SGD.MERCH_GROUP_CODE = \'SU\') OR (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 8500) OR  (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 8000 AND SGD.GROUP_NO = 8040) ) ) THEN \'Supermarket\'
	WHEN SGD.STORE IN (\'2223\') THEN \'Department Store\'
	WHEN SGD.STORE IN (\'2013\', \'2012\', \'4004\', \'3009\', \'3010\', \'3011\', \'4002\', \'3012\') THEN \'Supermarket\'
	WHEN SGD.STORE IN (\'2005\',\'2008\',\'2010\',\'2011\',\'6001\', \'6002\', \'6003\', \'6004\', \'6005\', \'6012\', \'6009\', \'6010\', \'6011\') THEN \'Hypermarket\'
	WHEN SGD.STORE IN (\'3001\', \'3007\', \'4003\', \'3002\', \'3003\', \'3004\', \'3005\', \'3006\') THEN \'Supermarket\'
	ELSE SGD.STORE_FORMAT_DESC END AS STORE_FORMAT_DESC,
CASE WHEN TO_CHAR(SGD.STORE) = \'4002\' THEN \'2001W\' 
	 ELSE TO_CHAR(SGD.STORE) END AS STORE_CODE,
SGD.STORE_NAME STORE_NAME, 
CASE WHEN (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 9000) THEN \'DS\'
     WHEN (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 8500) THEN \'SU\'
     WHEN (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 8000 AND SGD.GROUP_NO = 8040) THEN \'SU\'
     WHEN (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 8000 AND SGD.GROUP_NO != 8040) THEN \'DS\'
	 ELSE SGD.MERCH_GROUP_CODE END AS MERCH_GROUP_CODE,
CASE WHEN (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 9000) THEN \'DEPARTMENT STORE\'
     WHEN (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 8500) THEN \'SUPERMARKET\'
     WHEN (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 8000 AND SGD.GROUP_NO = 8040) THEN \'SUPERMARKET\'
     WHEN (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 8000 AND SGD.GROUP_NO != 8040) THEN \'DEPARTMENT STORE\'
	 ELSE SGD.MERCH_GROUP_DESC END AS MERCH_GROUP_DESC,
SGD.ATTRIB1 GROUP_CODE, 
SGD.ATTRIB2 GROUP_DESC, 
SGD.DIVISION, 
SGD.DIV_NAME DIVISION_DESC, 
SGD.GROUP_NO DEPARTMENT_CODE, 
SGD.GROUP_NAME DEPARTMENT_DESC,
NVL(SUM(STK.TOT_REPL_ITEMS),0) TOT_REPL_ITEMS, 
NVL(SUM(STK.REPL_WITH_SOH),0) REPL_WITH_SOH,
NEW_FLG,
MATURED_FLG,
REGION,
SYSDATE AS UPDATE_DATE
FROM
	(SELECT S.STORE_FORMAT, S.STORE_FORMAT_DESC, S.STORE, S.STORE_NAME, M.MERCH_GROUP_CODE, M.MERCH_GROUP_DESC, M.ATTRIB1, M.ATTRIB2, M.DIVISION, M.DIV_NAME, M.GROUP_NO, M.GROUP_NAME, NEW_FLG, MATURED_FLG, REGION
		FROM
			(SELECT A.STORE_FORMAT, F.FORMAT_NAME STORE_FORMAT_DESC, STORE, STORE_NAME, NEW_FLG, MATURED_FLG, REGION FROM 
				(SELECT DISTINCT STORE_FORMAT, STORE, STORE_NAME FROM STORE@RMS WHERE STORE NOT IN (\'6008\') 
				UNION ALL 
				SELECT DISTINCT 8 AS STORE_FORMAT, WH AS STORE, WH_NAME STORE_NAME FROM WH@RMS)A
				LEFT JOIN STORE_FORMAT F ON A.STORE_FORMAT = F.STORE_FORMAT
				LEFT JOIN (SELECT A.STORE_CODE, A.NEW_FLG, A.MATURED_FLG, A.REGION
						FROM DIM_STORE A 
							INNER JOIN (SELECT STORE_CODE, MAX(STORE_KEY) STORE_KEY FROM DIM_STORE GROUP BY STORE_CODE)B ON A.STORE_KEY = B.STORE_KEY AND A.STORE_CODE = B.STORE_CODE
						GROUP BY A.STORE_CODE, A.NEW_FLG, A.MATURED_FLG, A.REGION)TST ON A.STORE = TST.STORE_CODE)S,   
			(SELECT B.MERCH_GROUP_CODE, B.MERCH_GROUP_DESC, B.ATTRIB1 ATTRIB1, B.ATTRIB2, G.DIVISION, I.DIV_NAME, D.GROUP_NO, G.GROUP_NAME 
				FROM DEPS@RMS D 
				  JOIN GROUPS@RMS G ON D.GROUP_NO = G.GROUP_NO
				  JOIN DIVISION@RMS I ON G.DIVISION = I.DIVISION 
				  JOIN RMSPRD.BI_MERCH_GROUP@RMS B ON I.DIVISION = B.DIVISION
			 WHERE I.DIVISION NOT IN (4000))M
	GROUP BY S.STORE_FORMAT, S.STORE_FORMAT_DESC, S.STORE, S.STORE_NAME, M.MERCH_GROUP_CODE, M.MERCH_GROUP_DESC, M.ATTRIB1, M.ATTRIB2, M.DIVISION, M.DIV_NAME, M.GROUP_NO, M.GROUP_NAME, NEW_FLG, MATURED_FLG, REGION
	)SGD
	LEFT JOIN
	(SELECT GROUP_NO, LOCATION, LOC_NAME, COUNT(REPL_TAG) TOT_REPL_ITEMS, COUNT(STOCK_TAG) REPL_WITH_SOH
	FROM(
		SELECT DISTINCT DEPS.GROUP_NO, MST.DEPT, DEPT_NAME, REPL.ITEM, REPL.LOCATION, LOCATIONS.LOC_NAME, \'Y\' REPL_TAG, 
		  STOCK_ON_HAND, CASE WHEN STOCK_ON_HAND <= 0 THEN NULL ELSE \'Y\' END AS STOCK_TAG --DECODE(STOCK_ON_HAND,0,\'\',\'Y\') STOCK_TAG
		FROM REPL_ITEM_LOC@RMS REPL
			LEFT JOIN ITEM_LOC@RMS LOC ON REPL.ITEM=LOC.ITEM AND REPL.LOCATION=LOC.LOC
			LEFT JOIN ITEM_LOC_SOH@RMS SOH ON REPL.ITEM=SOH.ITEM AND REPL.LOCATION=SOH.LOC
			LEFT JOIN ITEM_MASTER@RMS MST ON REPL.ITEM=MST.ITEM 
			LEFT JOIN DEPS@RMS ON MST.DEPT=DEPS.DEPT
			LEFT JOIN GROUPS@RMS ON DEPS.GROUP_NO=GROUPS.GROUP_NO
			LEFT JOIN DIVISION@RMS D ON GROUPS.DIVISION = D.DIVISION
			LEFT JOIN RMSPRD.BI_MERCH_GROUP@RMS BI ON D.DIVISION = BI.DIVISION
			LEFT JOIN (SELECT DISTINCT STORE LOC, STORE_NAME LOC_NAME FROM STORE@RMS UNION ALL SELECT DISTINCT WH AS LOC, WH_NAME LOC_NAME FROM WH@RMS)LOCATIONS ON REPL.LOCATION=LOCATIONS.LOC
		WHERE LOC.STATUS IN (\'A\') AND DEPS.PURCHASE_TYPE = 0 --AND REPL.STOCK_CAT IN (\'C\',\'D\',\'W\')
	  AND REPL.ACTIVATE_DATE <= SYSDATE AND (REPL.DEACTIVATE_DATE IS NULL OR REPL.DEACTIVATE_DATE > SYSDATE)
      AND MST.ORDERABLE_IND = \'Y\' AND SOH.FIRST_RECEIVED IS NOT NULL  
      AND (
          (( BI.MERCH_GROUP_CODE=\'SU\' OR ((BI.MERCH_GROUP_CODE=\'OT\' AND D.DIVISION=8500) OR (BI.MERCH_GROUP_CODE=\'OT\' AND D.DIVISION=8000 AND GROUPS.GROUP_NO = 8040))) 
              AND (SYSDATE-SOH.LAST_RECEIVED) <= 91 ) 
            OR
          (( BI.MERCH_GROUP_CODE=\'DS\' OR ((BI.MERCH_GROUP_CODE=\'OT\' AND D.DIVISION=9000) OR (BI.MERCH_GROUP_CODE=\'OT\' AND D.DIVISION=8000 AND GROUPS.GROUP_NO != 8040))) 
              AND (SYSDATE-SOH.LAST_RECEIVED) <= 182 )
          )
	)TBL
	GROUP BY GROUP_NO, LOCATION, LOC_NAME)STK
	ON SGD.STORE = STK.LOCATION AND SGD.GROUP_NO = STK.GROUP_NO
GROUP BY 
CASE 
	WHEN (SGD.STORE IN (\'2001\', \'2002\', \'2003\', \'2004\', \'2006\', \'2007\', \'2009\') AND ( (SGD.MERCH_GROUP_CODE = \'DS\') OR (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 9000) OR  (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 8000 AND SGD.GROUP_NO != 8040) ) ) THEN \'1\'
	WHEN (SGD.STORE IN (\'2001\', \'2002\', \'2003\', \'2004\', \'2006\', \'2007\', \'2009\') AND ( (SGD.MERCH_GROUP_CODE = \'SU\') OR (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 8500) OR  (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 8000 AND SGD.GROUP_NO = 8040) ) ) THEN \'2\'
	WHEN SGD.STORE IN (\'2223\') THEN \'1\'
	WHEN SGD.STORE IN (\'2013\', \'2012\', \'4004\', \'3009\', \'3010\', \'3011\', \'4002\', \'3012\') THEN \'2\'
	WHEN SGD.STORE IN (\'2005\',\'2008\',\'2010\',\'2011\',\'6001\', \'6002\', \'6003\', \'6004\', \'6005\', \'6012\', \'6009\', \'6010\', \'6011\') THEN \'4\'
	WHEN SGD.STORE IN (\'3001\', \'3007\', \'4003\', \'3002\', \'3003\', \'3004\', \'3005\', \'3006\') THEN \'2\'
	ELSE TO_CHAR(SGD.STORE_FORMAT) END, 
CASE 
	WHEN (SGD.STORE IN (\'2001\', \'2002\', \'2003\', \'2004\', \'2006\', \'2007\', \'2009\') AND ( (SGD.MERCH_GROUP_CODE = \'DS\') OR (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 9000) OR  (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 8000 AND SGD.GROUP_NO != 8040) ) ) THEN \'Department Store\'
	WHEN (SGD.STORE IN (\'2001\', \'2002\', \'2003\', \'2004\', \'2006\', \'2007\', \'2009\') AND ( (SGD.MERCH_GROUP_CODE = \'SU\') OR (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 8500) OR  (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 8000 AND SGD.GROUP_NO = 8040) ) ) THEN \'Supermarket\'
	WHEN SGD.STORE IN (\'2223\') THEN \'Department Store\'
	WHEN SGD.STORE IN (\'2013\', \'2012\', \'4004\', \'3009\', \'3010\', \'3011\', \'4002\', \'3012\') THEN \'Supermarket\'
	WHEN SGD.STORE IN (\'2005\',\'2008\',\'2010\',\'2011\',\'6001\', \'6002\', \'6003\', \'6004\', \'6005\', \'6012\', \'6009\', \'6010\', \'6011\') THEN \'Hypermarket\'
	WHEN SGD.STORE IN (\'3001\', \'3007\', \'4003\', \'3002\', \'3003\', \'3004\', \'3005\', \'3006\') THEN \'Supermarket\'
	ELSE SGD.STORE_FORMAT_DESC END,
CASE WHEN TO_CHAR(SGD.STORE) = \'4002\' THEN \'2001W\' 
	 ELSE TO_CHAR(SGD.STORE) END,
SGD.STORE_NAME, 
CASE WHEN (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 9000) THEN \'DS\'
     WHEN (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 8500) THEN \'SU\'
     WHEN (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 8000 AND SGD.GROUP_NO = 8040) THEN \'SU\'
     WHEN (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 8000 AND SGD.GROUP_NO != 8040) THEN \'DS\'
	 ELSE SGD.MERCH_GROUP_CODE END,
CASE WHEN (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 9000) THEN \'DEPARTMENT STORE\'
     WHEN (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 8500) THEN \'SUPERMARKET\'
     WHEN (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 8000 AND SGD.GROUP_NO = 8040) THEN \'SUPERMARKET\'
     WHEN (SGD.MERCH_GROUP_CODE = \'OT\' AND SGD.DIVISION = 8000 AND SGD.GROUP_NO != 8040) THEN \'DEPARTMENT STORE\'
	 ELSE SGD.MERCH_GROUP_DESC END,
SGD.ATTRIB1, 
SGD.ATTRIB2, 
SGD.DIVISION, 
SGD.DIV_NAME, 
SGD.GROUP_NO, 
SGD.GROUP_NAME,
NEW_FLG,
MATURED_FLG, 
REGION
); 
 
EXECUTE IMMEDIATE \'TRUNCATE TABLE METRO_IT_INSTOCK_DEPT\';

FORALL i in instock_tab.first .. instock_tab.last
	INSERT INTO METRO_IT_INSTOCK_DEPT VALUES instock_tab(i);

COMMIT;

END;
';

my $sth = $dbh->prepare ($test);
$sth->execute;
 
$sth->finish();
$dbh->disconnect;

}

sub mail {

my $cc;
my $bcc;
GetOptions( 'cc=s' => \$cc, 'bcc=s' => \$bcc, );

my( $to, $subject, $from ) = @ARGV;


$to = 'rex.cabanilla@metroretail.com.ph,marlou.escanilla@metroretail.com.ph, joey.labrador@metroretail.com.ph, edsel.gayo@metroretail.com.ph, Dennis.Cuizon@metroretail.com.ph, rex.cabanilla@metroretail.com.ph,christopher.calalang@metroretail.com.ph,lloydpatrick.flores@metroretail.com.ph';

#$cc = 'lea.gonzaga@metroretail.com.ph';


$from = 'Report Mailer<report.mailer@metroretail.com.ph>';		

$subject = 'DSP Reports Notification';

my %mail = (
    To   => $to,
	From  => $from,
    Subject => $subject,
	'content-type' => "multipart/alternative; boundary=\"$boundary\""
);

$mail{smtp} = '10.190.1.30';
$mail{Cc} = $cc if $cc;
$mail{Bcc} = $bcc if $bcc;

my $boundary = "====" . time . "====";

$mail{'content-type'} = qq(multipart/mixed; boundary="$boundary");

$boundary = '--'.$boundary;

$mail{body} = 
<<END_OF_BODY;
$boundary
Content-Type: text/html; charset="iso-8859-1"

<html>
Hi All, <br> <br>
The following reports has been sent to users:<br> <br>
 1. Daily Sales Performance - Summary ( as of $as_of ) v1.7 <br> 
 2. Daily Sales Performance - Summary ( as of $as_of ) v2.7 <br> 
 3. Daily Sales Performance - Outright ( as of $as_of ) v1.3 <br> 
 4. Daily Sales Performance - Concession ( as of $as_of ) v1.3 <br> 
<br> <br>


Regards, <br>
ARC Admin <p>
</html>

$boundary--
END_OF_BODY

sendmail(%mail) or die $Mail::Sendmail::error;

print "Sendmail Log says:\n$Mail::Sendmail::log\n";

}


